default['postgis']['database_root_password'] = 'postgres'
default['postgis']['database'] = 'TEFENUA'
default['postgis']['database_user'] = 'postgres'
default['postgis']['database_user_password'] = 'postgres'
default['postgis']['src_link'] = 'http://download.osgeo.org/postgis/source/postgis-2.1.3.tar.gz'
default['postgis']['directory']['src'] = '/opt/postgis/src'
default['postgis']['bin'] = 'postgis-2.1.3.tar.gz'
default['postgis']['base_postgis_created'] = '/opt/postgis/src/base_postgis_created'
